version: '3.5'
services:
  friend-mgmt-mongodb:
    container_name: friend-mgmt-mongodb
    build:
      context: .
      dockerfile: Dockerfile.friend-mgmt-mongodb
    image: heavenhell81/friend-mgmt-mongodb:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - AUTH=no
      - MONGO_INITDB_DATABASE=friendmgmt
    volumes:
      - friend-mgmt-mongodb-volume:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles
      #  --logpath=/dev/null # --quiet
    networks:
      - friend-mgmt-network
    healthcheck:
      test: ["CMD", "/home/obs/friend-mgmt-mongodb-healthcheck.sh"]
      # first run interval seconds after the container is started, and then again interval seconds after each previous check completes
      interval: 30s
      timeout: 10s
      retries: 3
      # start period provides initialization time for containers that need time to bootstrap.
      start_period: 10s
  friend-mgmt-api:
    container_name: friend-mgmt-api
    build:
      context: .
      dockerfile: Dockerfile.friend-mgmt-api
    image: heavenhell81/friend-mgmt:latest
    entrypoint: ["/bin/bash",  "/home/obs/friend-mgmt-api-entrypoint.sh"]
    environment:
      APPLICATION_PORT: 8092
      MONGO_DB_HOST: friend-mgmt-mongodb
      MONGO_DB_PORT: 27017
    ports:
    - "8092:8092"
    networks:
    - friend-mgmt-network
    healthcheck:
      test: ["CMD", "/home/obs/friend-mgmt-api-healthcheck.sh"]
      # first run interval seconds after the container is started, and then again interval seconds after each previous check completes
      interval: 30s
      timeout: 10s
      retries: 3
      # start period provides initialization time for containers that need time to bootstrap.
      start_period: 10s
networks:
  friend-mgmt-network:
    # use the bridge driver
    driver: bridge
    name: friend-mgmt-network
    attachable: true
volumes:
  friend-mgmt-mongodb-volume:
